name: podman

on:
  push:
  workflow_dispatch:

jobs:
  node:
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest ]
    runs-on: ${{matrix.os}}
    defaults:
      run:
        working-directory: nodejs
    steps:
      - uses: actions/checkout@main
      - uses: actions/setup-node@main
        with:
          check-latest: true
          node-version: lts/*
      - uses: davidkhala/setup-podman@main
      - run: podman context ls
      - run: npm i
      - run: npm test
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Log in to ghcr.io
        uses: redhat-actions/podman-login@main
        with:
          username: ${{ github.actor }}
          password: ${{ github.token }}
          registry: ghcr.io/${{ github.repository_owner }}
