## "GitHub's Ubuntu action runners come with Podman preinstalled". See in https://github.com/redhat-actions/podman-login
name: podman


on:
  push:
  workflow_dispatch:

jobs:
  node:
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest ]
    runs-on: ${{matrix.os}}
    defaults:
      run:
        working-directory: nodejs
    steps:
      - uses: actions/checkout@main
      - uses: actions/setup-node@main
        with:
          check-latest: true
          node-version: lts/*
      - run: podman machine init --now
      - run: podman context ls
      - run: npm i
      - run: npm test
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Log in to ghcr.io
        uses: redhat-actions/podman-login@main
        with:
          username: ${{ github.actor }}
          password: ${{ github.token }}
          registry: ghcr.io/${{ github.repository_owner }}
  setup:
    runs-on: ubuntu-latest
    env:
      QEMU_ACCEL: tcg
    steps:
      - uses: actions/checkout@main
      - run: sudo apt update
      - run: sudo apt install -y -q qemu-system-x86 gvproxy
      - run: sudo mv /usr/bin/qemu-system-x86_64 /usr/bin/qemu-system-x86_64.real
      - run: sudo mv ./.github/workflows/qemu-system-x86_64 /usr/bin/qemu-system-x86_64
      - run: sudo ln -s /usr/bin/gvproxy /usr/libexec/podman/gvproxy
      - run: podman machine init --user-mode-networking --now
      - run: podman context ls



