name: sdks

on:
  push:
  workflow_dispatch:

jobs:
  node:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{matrix.os}}
    defaults:
      run:
        working-directory: nodejs
    steps:
      - uses: actions/checkout@main
      - uses: actions/setup-node@main
        with:
          check-latest: true
          node-version: lts/*
      - uses: davidkhala/setup-podman@main
      - run: npm i
      - run: npm test
